# Generated by Django 2.0.8 on 2018-09-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_interface_mtu'),
        ('ipam', '0023_change_logging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrf',
            name='tenant',
        ),
        migrations.AddField(
            model_name='vrf',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vrfs', to='dcim.Device'),
        ),
    ]
